# Generated by Django 4.2.2 on 2023-06-17 16:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user_rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating_news',
        ),
        migrations.AddField(
            model_name='post',
            name='image_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='video_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='tematic',
            field=models.CharField(choices=[('TN', 'Танк'), ('HL', 'Хил'), ('DD', 'ДД'), ('GM', 'Гилдмастер'), ('KG', 'Квестгивер'), ('KZ', 'Кузнец'), ('KV', 'Кожевник'), ('ZV', 'Зельевар'), ('MZ', 'Мастер заклинаний')], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_news',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
