# Generated by Django 4.2.2 on 2023-06-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='text',
        ),
    ]
